<a href="https://colab.research.google.com/github/da-matsumoto/machine/blob/practice/numpytest.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [9]:
import numpy as np

a = np.array([1, 2, 3])
a
type(a)
print(a)
a.shape

[1 2 3]


(3,)

In [8]:
import numpy as np

b = np.array([[1, 2, 3], [4, 5, 6]])
b
print(b)
b.shape

[[1 2 3]
 [4 5 6]]


(2, 3)

In [16]:
a = np.array([1, 2, 3])
b = np.array([[1, 2, 3], [4, 5, 6]])

print(a[0])
print(a[-1])
print(b[0])
print(b[1, 0])
print(a[1:])
print(b[:, 2])
print(b[1, :])

1
3
[1 2 3]
4
[2 3]
[3 6]
[4 5 6]


In [20]:
a = np.array([1, 2, 3])
a[2] = 4
print(a)

b = np.array([[1, 2, 3], [4, 5, 6]])
b[1, 2] = 7
print(b)
b[:, 2] = 8
print(b)

[1 2 4]
[[1 2 3]
 [4 5 7]]
[[1 2 8]
 [4 5 8]]
