<a href="https://colab.research.google.com/github/da-matsumoto/machine/blob/practice/numpytest.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

a = np.array([1, 2, 3])
a
type(a)
print(a)
a.shape

[1 2 3]


(3,)

In [ ]:
import numpy as np

b = np.array([[1, 2, 3], [4, 5, 6]])
b
print(b)
b.shape

[[1 2 3]
 [4 5 6]]


(2, 3)

In [ ]:
a = np.array([1, 2, 3])
b = np.array([[1, 2, 3], [4, 5, 6]])

print(a[0])
print(a[-1])
print(b[0])
print(b[1, 0])
print(a[1:])
print(b[:, 2])
print(b[1, :])

1
3
[1 2 3]
4
[2 3]
[3 6]
[4 5 6]


In [ ]:
a = np.array([1, 2, 3])
a[2] = 4
print(a)

b = np.array([[1, 2, 3], [4, 5, 6]])
b[1, 2] = 7
print(b)
b[:, 2] = 8
print(b)

[1 2 4]
[[1 2 3]
 [4 5 7]]
[[1 2 8]
 [4 5 8]]


In [ ]:
import numpy as np
a = np.array([1, 2, 3])
print(np.sum(a))
print(a.sum())
print(a.dtype)
a.astype(np.float16)

6
6
int64


array([1., 2., 3.], dtype=float16)

In [ ]:
import numpy as np
c1 = np.array([1, 2, 3, 4, 5, 6])
print(c1) 
c2 = c1.reshape((2, 3))
print(c2)
c3 = c2.ravel()
print(c3)
c4 = c2.flatten()
print(c4)

[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]
[1 2 3 4 5 6]


In [ ]:
import numpy as np
a = np.array([1, 2, 3])
print(a)
a1 = a
a1[2] = 5
print(a1)
print(a)
a2 = a.copy()
print(a2)
a2[2] = 10
print(a2)
print(a)

[1 2 3]
[1 2 5]
[1 2 5]
[1 2 5]
[ 1  2 10]
[1 2 5]


In [ ]:
import numpy as np
np.arange(10)
np.arange(1, 11)
np.arange(1, 11, 2)

array([1, 3, 5, 7, 9])

In [ ]:
import numpy as np
f_array = np.random.random((4, 2))
print(f_array)
np.random.seed(123)
print(np.random.random((4, 2)))

[[0.4809319  0.39211752]
 [0.34317802 0.72904971]
 [0.43857224 0.0596779 ]
 [0.39804426 0.73799541]]
[[0.69646919 0.28613933]
 [0.22685145 0.55131477]
 [0.71946897 0.42310646]
 [0.9807642  0.68482974]]


In [ ]:
import numpy as np
np.random.seed(123)
print(np.random.randint(1, 10))
print(np.random.randint(1, 10, (3, 5)))

3
[[3 7 2 4 7]
 [2 1 2 1 1]
 [4 5 1 1 5]]


In [ ]:
import numpy as np
np.random.seed(123)
print(np.random.uniform(0.0, 5.0, size=(4, 2)))

print(np.random.randn(4, 3))

[[3.48234593 1.43069667]
 [1.13425727 2.75657385]
 [3.59734485 2.1155323 ]
 [4.90382099 3.42414869]]
[[-2.42667924 -0.42891263  1.26593626]
 [-0.8667404  -0.67888615 -0.09470897]
 [ 1.49138963 -0.638902   -0.44398196]
 [-0.43435128  2.20593008  2.18678609]]


In [ ]:
import numpy as np
print(np.zeros((3,4)))
print(np.ones((2, 4)))
print(np.eye(4))
print(np.full(5, 10))
print(np.full((2, 3), np.pi))
print(np.linspace(0, 1, 5))

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[10 10 10 10 10]
[[3.14159265 3.14159265 3.14159265]
 [3.14159265 3.14159265 3.14159265]]
[0.   0.25 0.5  0.75 1.  ]


In [13]:
import numpy as np
l = np.array([1, 2, 3, 4, 5])
print(np.diff(l))

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
ab = np.concatenate([a, b])
print(ab)

c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[10, 20], [30, 40]])
cd = np.concatenate([c, d], axis=1)
print(cd)

e = np.array([[1, 2, 3], [4, 5, 6]])
f = np.array([[10, 20, 30], [40, 50, 60]])
ef = np.vstack([e, f])
print(ef)

[1 1 1 1]
[1 2 3 4 5 6]
[[ 1  2  3 10 20]
 [ 4  5  6 30 40]]
[[ 1  2  3]
 [ 4  5  6]
 [10 20 30]
 [40 50 60]]


In [15]:
import numpy as np
a = np.array([[1, 2, 10], [3, 4, 20], [5, 6, 30], [7, 8, 40]])

col1, col2 = np.hsplit(a, [2])
print(col1)
print(col2)

row1, row2 = np.vsplit(a, [2])
print(row1)
print(row2)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[10]
 [20]
 [30]
 [40]]
[[ 1  2 10]
 [ 3  4 20]]
[[ 5  6 30]
 [ 7  8 40]]


In [16]:
import numpy as np
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(a.T)

[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [19]:
import numpy as np
a = np.array([1, 2, 3])
print(a[np.newaxis, :])
print(a[:, np.newaxis])

[[1 2 3]]
[[1]
 [2]
 [3]]


In [21]:
import numpy as np

x = np.array([1, 2, 3, 4])
y = np.array([5, 6, 7])

xx, yy = np.meshgrid(x, y)

print(xx)
print(yy)

[[1 2 3 4]
 [1 2 3 4]
 [1 2 3 4]]
[[5 5 5 5]
 [6 6 6 6]
 [7 7 7 7]]
